# Generated by Django 5.2 on 2025-04-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_alter_survey_interest_source_alter_survey_liked_most_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='recommend_likelihood',
            field=models.CharField(max_length=50),
        ),
    ]
